spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/steamapps
    username: doko
    password: ''
    initialization-mode: always

server:
  port: 8080
